config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "publics#index"
  
  resources :recipes, only: [:index, :show, :new, :destroy, :create, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  
  resources :inventories, only: [:index, :show, :new, :destroy, :create] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  
  resources :foods, only: [:index, :show, :new, :destroy, :create]

  resources :publics, only: [:index]
  
  get "/shopping_list", to: "foods#shopping_list"

end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
  validates_uniqueness_of :name
  validates :name, presence: true, length: { maximum: 100 }
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @inventories = Inventory.all.where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @inventory = Inventory.new
  end

  def show
    @inventory = Inventory.find(params[:id])
    @inventory_foods = Food.all.joins('INNER JOIN inventory_foods ON foods.id = inventory_foods.food_id')
      .order(created_at: :desc).select('foods.*, inventory_foods.quantity, inventory_foods.id as inventory_food_id')
      .where(inventory_foods: { inventory_id: params[:id] }).with_attached_image
  end

  def create
    inventory = Inventory.new(inventory_params)
    inventory.user_id = current_user.id
    if inventory.save
      flash.now[:success] = 'Inventory was successfully created.'
      redirect_to inventories_path
    else
      flash.now[:danger] = 'Inventory was not created because <ul class="error-list">'
      inventory.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
      render :new
    end
  end

  def destroy
    @inventories = Inventory.all.where(user_id: current_user.id).order(created_at: :desc)
    inventory_to_delete = Inventory.find(params[:id])
    if inventory_to_delete.destroy
      flash.now[:success] = 'Inventory was successfully deleted.'
    else
      flash.now[:danger] = 'Inventory was not deleted because <ul class="error-list">'
      new_food.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
    end
    render :index
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/views/inventories/index.html.erb
<h4> All inventories (<%= @inventories.length %>)</h4>
<hr />
<% if @inventories.empty? %>
    <div class="row">
        <div class="mb-3 col-md-8 offset-md-2 inventory-card shadow">
            No inventories yet
        </div>
    </div>
<% else %>
 <% @inventories.each do |inventory| %>
    <%= link_to inventory_path(inventory.id), class: "card-link" do %>
        <div class="row">
            <div class="mb-3 col-md-8 offset-md-2 inventory-card shadow">
                <div class="row p-3">
                    <div class="col-md-4">
                        <h5>
                            <%= inventory.name %>
                        </h5>
                        <%= link_to inventory_path(inventory.id), class: "btn btn-primary" do %>
                            <i class="fa fa-eye" aria-hidden="true"></i> View
                        <% end %>
                        <% if can? :destroy, inventory %>
                            <a href="<%= inventory_path(inventory.id) %>" data-confirm="Delete inventory [<%= inventory.name %>]?" data-method="delete" class='btn btn-danger'>
                                <i class="fa fa-trash trash shadow" aria-hidden="true"></i> Delete
                            </a>
                        <% end %>
                    </div>
                    <div class="col-md-8">
                        <%= inventory.description %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
 <% end %>
<% end %>

app/views/inventories/new.html.erb
<div class="row">
    <div class="mb-3 col-md-8 offset-md-2 inventory-card shadow">
        <%= image_tag("create-inventory.png", class: "card-img-top") %>
        <div class="card-body">
        <h5 class="card-title">Add New Inventory</h5>
        <p class="card-text">Use this to add storage for a complete list of food items available to make recipes </p>
        <%= form_with model: @inventory, url: inventories_path, local: true do |form| %>
            <div class="form-floating mb-3">
                <%= form.text_field :name, class: "form-control", required: true %>
                <%= form.label :name, "Inventory Name *" %>
            </div>
            <div class="form-floating mb-3">
                <%= form.text_area :description, size: "70x5", class: "form-control" %>
                <%= form.label :description, "How would you describe this inventory" %>
            </div>
            <div class="form-group mt-3">
                <%= form.submit 'Add Inventory', class: "btn btn-accent", data: {disable_with: "Loading..."} %>
            </div>
        <% end %>
        <p class="card-text"><small class="text-muted">Updating as <%= current_user.name %></small></p>
        </div>
  </div>
</div>

app/views/inventories/show.html.erb
<%= link_to ' << Back to all inventories', inventories_path, class: "btn btn-outline-success mb-2" %> 
<h4><%= @inventory.name %></h4>

<div class="table-responsive mt-1">
<div style="float: right;">
    <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Add food to inventory'.html_safe, new_inventory_inventory_food_path(@inventory.id), class: "btn btn-accent mb-2" %> 
</div>
  <table class="table table-striped text-center">
    <thead>
      <tr>
        <th>#</th>
        <th>Food</th>
        <th>Quantity</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @inventory_foods.each do |inventory_food| %>
        <tr>
          <td>
            <% if inventory_food.image.present? %>
              <%= image_tag inventory_food.image, class: "bio-photo" %>
            <% else %>
              <%= image_tag "https://nuwaay.com/wp-content/uploads/2022/01/default_256.png", class: "bio-photo" %>
            <% end %>
          </td>
          <td><%= inventory_food.name %></td>
          <td><%= inventory_food.quantity %><%= inventory_food.measurement_unit %></td>
          <td>
            <a href="<%= inventory_inventory_food_path(@inventory.id, inventory_food.inventory_food_id) %>" data-confirm="Are you sure you want to delete <%= inventory_food.name %> from this inventory?" data-method="delete" class='btn btn-danger'>Delete</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
  </table>
</div>