config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "publics#index"
  
  resources :recipes, only: [:index, :show, :new, :destroy, :create, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  
  resources :inventories, only: [:index, :show, :new, :destroy, :create] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  
  resources :foods, only: [:index, :show, :new, :destroy, :create]

  resources :publics, only: [:index]
  
  get "/shopping_list", to: "foods#shopping_list"

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true

  has_one_attached :image
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  load_and_authorize_resource

  def index
    @recipes = Recipe.all.where(user_id: current_user).order(created_at: :desc).with_attached_image
  end

  def show
    data = Recipe.where(id: params[:id]).with_attached_image
    @recipe = data[0]
    @recipe_foods = Food.all.joins('INNER JOIN recipe_foods ON foods.id = recipe_foods.food_id')
      .order(created_at: :desc).select('foods.*, recipe_foods.quantity, recipe_foods.id as recipe_foods_id')
      .where(recipe_foods: { recipe_id: params[:id] }).with_attached_image
    return unless current_user

    @inventory_hash = Inventory.all.where(user_id: current_user.id).map { |inventory| [inventory.name, inventory.id] }
  end

  def new
    @user = current_user
    @recipe = @user.recipes.new
  end

  def update
    Recipe.find(params[:id]).update(public: params[:recipe][:public])
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)
    @recipe.preparation_time = "#{params[:recipe][:preparation_time]} minute(s)"
    @recipe.cooking_time = "#{params[:recipe][:cooking_time]} minute(s)"

    respond_to do |format|
      format.html do
        if @recipe.save
          flash[:success] = 'Recipe created successfully'
          redirect_to recipes_url
        else
          flash.now[:danger] = 'Recipe was not created because <ul class="error-list">'
          @recipe.errors.full_messages.each do |msg|
            flash.now[:danger] += "<li>#{msg}</li>"
          end
          flash.now[:danger] += '</ul>'
          render :new
        end
      end
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    if recipe.destroy
      flash[:success] = 'Recipe deleted successfully'
    else
      flash.now[:danger] = 'Recipe deleted because <ul class="error-list">'
      recipe.errors.full_messages.each do |msg|
        flash[:danger] += "<li>#{msg}</li>"
      end
      flash[:danger] += '</ul>'
    end
    redirect_to recipes_url
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description, :image)
  end
end

app/views/recipes/index.html.erb
<h5 class="mb-2">Your Recipies (<%= @recipes.length %>)</h5>
<hr />
<div class="row">
    <% @recipes.each do |recipe| %>
     <%= render partial: "shared/recipe_display", locals: {recipe: recipe} %>
    <% end %>
</div>

app/views/recipes/new.html.erb
<div class="row  container-fluid">
    <div class="mb-3 col-md-8 offset-md-2 inventory-card shadow">
        <%= image_tag("recipe-box-banner.jpg", class: "card-img-top") %>
        <div class="card-body">
        <h5 class="card-title">😊 Create a new recipe!!</h5>
        <p class="card-text"> Would'nt it be nice to store a recipe of your favourite food? Go ahead!</p>
            <%= form_with model: @recipe, url: recipes_path do |f| %>
                <div class="mb-3">
                    <%= f.file_field :image, class: 'form-control' %>
                    <%= f.label :image, 'Choose an image that would appear as banner for recipe', class: 'mb-2' %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.text_field :name, class: 'form-control', required: true %>
                    <%= f.label :name, "Recipe Name*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.number_field :preparation_time, class: 'form-control', required: true %>
                    <%= f.label :preparation_time, "Preparation Time in mins*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.number_field :cooking_time, class: 'form-control', required: true %>
                    <%= f.label :cooking_time, "Cooking Time in mins*" %>
                </div>
                <div class="form-floating mb-3">
                    <%= f.text_area :description, class: 'form-control' %>
                    <%= f.label :description, "Description" %>
                </div>
                <div class="form-check form-switch">
                    <%= f.check_box :public, class: "form-check-input" %>
                    <%= f.label :public, 'Mark public', class: "form-check-label" %> <br />
                    <i style="color: var(--primary-color)"> This allows other users to see your recipe</i>
                </div>
                <div class="form-group mt-3">
                    <%= f.submit '🥣 Create Recipe', class: "btn", style: "background-color: var(--primary-color); color: var(--white);", data: {disable_with: "Loading..."} %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/recipes/show.html.erb
<%= link_to ' << Public Recipes', publics_path, class: "btn btn-outline mb-2"%> 
<%= link_to ' << Recipes', recipes_path, class: "btn btn-outline mb-2" if current_user %> 
<div class="container">
    <div class="card text-center ">
        <h4 class="card-header" style="background: var(--primary-color); color: var(--white)">
          <%= image_tag @recipe.image, class: "float-start bio-photo" if @recipe.image.present? %>
          <%= @recipe.name %>
        </h4>
        <div class="row mx-5 mt-2">
          <div class="col-md-9">
              <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Preparation time: <%= @recipe.preparation_time %></p>
              <p class="text-start"><i class="fa fa-clock-o" aria-hidden="true"></i> Cooking time: <%= @recipe.cooking_time %></p> 
          </div>
          <% if current_user && @recipe.user_id == current_user.id %>
            <div class="col-md-3">
                <%= form_with model: @recipe, url: recipe_path(@recipe.id), method: :patch, local: true do |form| %>
                  <div class="form-switch">
                      <%= form.check_box :public, class: "form-check-input", onchange: 'this.form.submit()' %>
                      <%= form.label :public, 'public', class: "form-check-label", checked: @recipe.public %> <br />
                  </div>
                <% end %>
            </div>
          <% end %>
        </div>
    </div>
    <% if current_user && @recipe.user_id == current_user.id %>
      <div class="mt-4">
          <button type="button"class='btn btn-outline-primary mb-2 flex-start' data-bs-toggle="modal" data-bs-target="#listBackdrop">
            <i class="fa fa-shopping-basket" aria-hidden="true"></i> Generate shopping list
          </button>
          <span style="float: right">
            <%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Add food ingredient'.html_safe, new_recipe_recipe_food_path(@recipe.id), class: "btn btn-outline-success mb-2 flex-end" %> 
          </span>
      </div>
    <% end %>
    <table class="table table-striped text-center">
    <thead>
      <tr>
        <th class="text-center">#</th>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <% if current_user && @recipe.user_id == current_user.id %>
          <th>Action</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
          <% @recipe_foods.each do |recipe_food| %>
        <tr>
          <td>
              <% if recipe_food.image.present? %>
                <%= image_tag recipe_food.image, class: "bio-photo" %>
              <% else %>
                <%= image_tag "no-food-image.png", class: "bio-photo" %>
              <% end %>
          </td>
          <td><%= recipe_food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td>$<%= recipe_food.price * recipe_food.quantity %></td>
          <% if current_user && @recipe.user_id == current_user.id %>
            <td>
              <a href="<%= edit_recipe_recipe_food_path(@recipe.id, recipe_food.recipe_foods_id) %>" class='btn btn-outline-primary'>
                <i class="fa fa-pencil" aria-hidden="true"></i>  
                Modify
              </a>
              <a href="<%= recipe_recipe_food_path(@recipe.id, recipe_food.recipe_foods_id) %>" data-confirm="Delete <%= recipe_food.name %> from this recipe?" data-method="delete" class='btn btn-outline-danger'>
                <i class="fa fa-trash" aria-hidden="true"></i>
                Delete
              </a>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if current_user && @recipe.user_id == current_user.id %>
<%= render partial: "shared/shopping_list_setup", locals: { list: @inventory_hash, recipe: @recipe.id } %>
<% end %>