config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "publics#index"
  
  resources :recipes, only: [:index, :show, :new, :destroy, :create, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  
  resources :inventories, only: [:index, :show, :new, :destroy, :create] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  
  resources :foods, only: [:index, :show, :new, :destroy, :create]

  resources :publics, only: [:index]
  
  get "/shopping_list", to: "foods#shopping_list"

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
  has_many :recipe_foods, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 100 }
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates_uniqueness_of :name
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc).with_attached_image
  end

  def new
    @food = Food.new
  end

  def shopping_list
    @recipe = Recipe.find(params[:recipe_id])
    @inventory = Inventory.find(params[:inventory_id])

    # get all inventory foods
    # get all recipe foods
    # get all recipe foods that are not in inventory
    # get all recipe foods that the quantity is higher than the inventory quantity
    # a shopping list is made up of a combination of items
    # that do not exist in the inventory and items that are not enough in the inventory

    @recipe_foods = Food.all.joins('INNER JOIN recipe_foods ON foods.id = recipe_foods.food_id')
      .order(created_at: :desc).select('foods.*, recipe_foods.quantity, recipe_foods.id as recipe_foods_id')
      .where(recipe_foods: { recipe_id: params[:recipe_id] })

    @inventory_foods = Food.all.joins('INNER JOIN inventory_foods ON foods.id = inventory_foods.food_id')
      .select('foods.*, inventory_foods.quantity, inventory_foods.id as inventory_foods_id')
      .where(inventory_foods: { inventory_id: params[:inventory_id] })

    @recipe_food_with_quantity_greater_than_inventory_food_quantity = []
    @recipe_foods.select do |recipe_food|
      @inventory_foods.select do |inventory_food|
        if recipe_food.id == inventory_food.id && recipe_food.quantity > inventory_food.quantity
          recipe_food.quantity = recipe_food.quantity - inventory_food.quantity
          @recipe_food_with_quantity_greater_than_inventory_food_quantity << recipe_food
        end
      end
    end

    @recipe_foods_not_in_inventory = @recipe_foods - @inventory_foods

    @shopping_list = @recipe_foods_not_in_inventory + @recipe_food_with_quantity_greater_than_inventory_food_quantity

    @cost = 0
    @shopping_list.each do |list|
      @cost += list.price * list.quantity
    end
  end

  def create
    new_food = Food.new(food_params)
    new_food.user_id = current_user.id

    if new_food.save
      flash.now[:success] = 'Food was successfully created.'
    else
      flash.now[:danger] = 'Food was not created because <ul class="error-list">'
      new_food.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
    end
    render :new
  end

  def destroy
    @foods = Food.all.where(user_id: current_user.id).order(created_at: :desc).with_attached_image

    food_to_delete = Food.find(params[:id])
    if food_to_delete.destroy
      flash.now[:success] = 'Food was successfully deleted.'
    else
      flash.now[:danger] = 'Food was not deleted because <ul class="error-list">'
      new_food.errors.full_messages.each do |msg|
        flash.now[:danger] += "<li>#{msg}</li>"
      end
      flash.now[:danger] += '</ul>'
    end
    render :index
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :image)
  end

  private :food_params
end

app/views/foods/index.html.erb
<h5 class="card-title">List of foods</h5>
<div class="table-responsive">
  <table class="table table-striped text-center">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td>
            <% if food.image.present? %>
              <%= image_tag food.image, class: "bio-photo" %>
            <% else %>
              <%= image_tag "https://nuwaay.com/wp-content/uploads/2022/01/default_256.png", class: "bio-photo" %>
            <% end %>
          </td>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.price %></td>
          <td>
            <a href="<%= food_path(food.id) %>" data-confirm="Are you sure you want to delete <%= food.name %>?" data-method="delete" class='btn btn-danger'>Delete</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</table>
</div>

app/views/foods/new.html.erb
<div class="row">
    <div class="mb-3 col-md-8 offset-md-2">
    <div class="row g-0">
        <div class="col-md-12 background shadow">
            <div class="card-body transbox">
                <h5 class="card-title">Add Food to your store</h5>
                <%= form_with model: @food, url: foods_path, local: true do |form| %>
                    <div class="form-floating mb-3">
                        <%= form.file_field :image, class: 'form-control' %>
                        <%= form.label :image, 'Image if any', class: 'p-2' %>
                    </div>
                    <div class="form-floating mb-3">
                        <%= form.text_field :name, class: "form-control", required: true %>
                        <%= form.label :name, "Name of Food *" %>
                    </div>
                    <div class="form-floating mb-3">
                        <%= form.select :measurement_unit, [['grams', 'g'], ['kilograms', 'kg'], ['milligrams', 'ml'], ['liter', 'l'], ['ounces', 'oz'], ['pound', 'lb'], ['cup', 'cup'], ['pint', 'pint'], ['quart', 'quart'], ['gallon', 'gallon']], {:include_blank => "-", :required => true}, {:class => 'form-control'} %>
                        <%= form.label :measurement_unit, "Choose measuring unit *" %>
                    </div>
                    <div class="form-floating mb-3">
                        <%= form.number_field :price, class: "form-control", required: true %>
                        <%= form.label :price, "Unit price($) *" %>
                    </div>
                    <div class="form-group mt-3">
                        <%= form.submit '🥣 Add Food', class: "btn", style: "background-color: var(--primary-color); color: var(--white);", data: {disable_with: "Loading..."} %>
                    </div>
                <% end %>
                <p class="card-text"><small class="text-muted">updating as <%= current_user.name %></small></p>
            </div>
        </div>
    </div>
    </div>
</div>

app/views/foods/shopping_list.html.erb
<%= link_to ' << Recipe', recipe_path(@recipe.id), class: "btn btn-outline-success mb-2" %> 
<div class="card col-md-6 offset-md-3">
  <div class="card-body">
    <div class="container">
      <p style="font-size: 30px; text-align:center; color: var(--primary-color)">Shopping list</p>
      <div class="row">
        <ul class="list-unstyled">
          <li class="text-black"><%= @recipe.name %></li>
          <li class="text-muted mt-1"><%= @inventory.name %></li>
          <li class="text-black mt-1">Items to purchase: <%= @shopping_list.length %></li>
          <li class="text-black mt-1">Total Cost: <%= "$#{@cost}" %></li>
        </ul>
      </div>
      <div class="row">
        <div class="col-xl-5">
            <b>Item</b>
        </div>
        <div class="col-xl-5">
            <b>Quantity</b>
        </div>
        <div class="col-xl-2">
            <b class="float-end">Price </b>
        </div>
        <hr>
     </div>
      <% @shopping_list.each do |food| %>
        <div class="row">
            <div class="col-xl-5">
                <p><%= food.name %></p>
            </div>
            <div class="col-xl-5">
                <p><%= "#{food.quantity} #{food.measurement_unit}" %></p>
            </div>
            <div class="col-xl-2">
                <p class="float-end"> $<%= food.quantity * food.price %> </p>
            </div>
            <hr>
        </div>
     <% end %>
      <div class="text-center" style="margin-top: 10px;">
        <a onclick="window.print(); return false;" style="cursor:pointer"><u class="text-primary"><i class="fa fa-print" aria-hidden="true"></i>Print</u></a>
        <p>Thank you for using our product</p>
      </div>

    </div>
  </div>
</div>