config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "publics#index"
  
  resources :recipes, only: [:index, :show, :new, :destroy, :create, :update] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  
  resources :inventories, only: [:index, :show, :new, :destroy, :create] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end
  
  resources :foods, only: [:index, :show, :new, :destroy, :create]

  resources :publics, only: [:index]
  
  get "/shopping_list", to: "foods#shopping_list"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag :application %>
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <nav class="navbar navbar-expand-lg mb-3" style="background-color: var(--accent-color)">
        <div class="container">
          <%= link_to "RecipeBook", root_path, :"data-turbolinks" => false, class: "navbar-brand display-6" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">    
              <li class="nav-item">
                <%= link_to "Public Recipes", publics_path, :"data-turbolinks" => false, class: "nav-link" %>
              </li>
              <% if current_user %> 
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbo="false">
                    Recipe
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to "My Recipes", recipes_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Add Recipe", new_recipe_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbo="false">
                    Foods
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to "My Foods", foods_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Add Food", new_food_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-turbo="false">
                    Inventories
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><%= link_to "My Inventories", inventories_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Add Inventory", new_inventory_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                  </ul>
                </li>
              <% end %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  My Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <% if current_user %>
                    <li> <%= link_to "My Profile", edit_user_registration_path, :"data-turbolinks" => false, class: "nav-link" %></li>
                    <li><%= button_to '<i class="fa fa-sign-out" aria-hidden="true"></i>Sign Out'.html_safe, destroy_user_session_path, method: :delete, :"data-turbolinks" => false, class: "nav-link link-btn" %></li>
                  <% else %>
                    <li><%= link_to '<i class="fa fa-sign-in" aria-hidden="true"></i> Sign In'.html_safe, new_user_session_path, :"data-turbolinks" => false, class: "nav-link" %></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Become a member", new_user_registration_path, :"data-turbolinks" => false, class: "dropdown-item" %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
            <div class="d-flex flex-column">
              <div class="d-flex flex-row align-items-center">
                  <div>
                    <% if current_user %>
                      <% if current_user.image.present? %>
                        <%= image_tag current_user.image, class: "bio-photo" %>
                      <% else %>
                      <%= image_tag "https://cdn.pixabay.com/photo/2016/04/01/10/11/avatar-1299805__340.png", class: "bio-photo" %>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="d-flex flex-column user-details">
                    <span><%= current_user.name if current_user %></span>
                    <span><%= current_user.email if current_user %></span>
                  </div>
              </div> 
            </div>
          </div>
        </div>
      </nav>
      <section class="container">
        <% if flash.any? %>
          <% flash.each do |type, msg| %>
            <div class="alert alert-<%= type %> text-center">
              <%= msg.html_safe %>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
    </div>
  </body>
  <footer>
      Copyright &copy; <%= Time.now.year %> Developed by Clinton Mbonu & Samuel Chimfwembe
  </footer>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash.any? %>
        <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %> text-center">
            <%= msg.html_safe %>
        </div>
        <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>